[package]
name = "toucan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "0.17"

[build-dependencies]
ethers-solc = "0.17"
